// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using project56.model;
using System;

namespace project56.Migrations
{
    [DbContext(typeof(LegoContext))]
    partial class LegoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("project56.model.Lego", b =>
                {
                    b.Property<int>("Item_Number")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Availability");

                    b.Property<int>("EUR_MSRP");

                    b.Property<int>("GB_MSRP");

                    b.Property<string>("Image_URL");

                    b.Property<int>("Minifigures");

                    b.Property<string>("Name");

                    b.Property<string>("Packaging");

                    b.Property<int>("Pieces");

                    b.Property<string>("Subtheme");

                    b.Property<string>("Theme");

                    b.Property<int>("USD_MSRP");

                    b.Property<int>("Year");

                    b.HasKey("Item_Number");

                    b.ToTable("legodetails");
                });
#pragma warning restore 612, 618
        }
    }
}
